#ifndef __S2_CNEIBIO_H__
#define __S2_CNEIBIO_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_CNEIBIO_TRIGGER_DIG_INPUT 0


/*
* ANALOG_INPUT
*/

#define __S2_CNEIBIO_COMMAND_STRING_INPUT 1
#define __S2_CNEIBIO_COMMAND_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_CNEIBIO, __COMMAND, __S2_CNEIBIO_COMMAND_STRING_MAX_LEN );

#define __S2_CNEIBIO_GATEWAYRX_BUFFER_INPUT 0
#define __S2_CNEIBIO_GATEWAYRX_BUFFER_MAX_LEN 50
CREATE_STRING_STRUCT( S2_CNEIBIO, __GATEWAYRX, __S2_CNEIBIO_GATEWAYRX_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/
#define __S2_CNEIBIO_IDLE_DIG_OUTPUT 0


/*
* ANALOG_OUTPUT
*/

#define __S2_CNEIBIO_GATEWAYTX_STRING_OUTPUT 0
#define __S2_CNEIBIO_FEEDBACK_STRING_OUTPUT 1


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_CNEIBIO_ADR_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_CNEIBIO, __ADR, __S2_CNEIBIO_ADR_STRING_MAX_LEN );
#define __S2_CNEIBIO_PARMS_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_CNEIBIO, __PARMS, __S2_CNEIBIO_PARMS_STRING_MAX_LEN );
#define __S2_CNEIBIO_ANSWER$_STRING_MAX_LEN 195
CREATE_STRING_STRUCT( S2_CNEIBIO, __ANSWER$, __S2_CNEIBIO_ANSWER$_STRING_MAX_LEN );
#define __S2_CNEIBIO_PACK$_STRING_MAX_LEN 25
CREATE_STRING_STRUCT( S2_CNEIBIO, __PACK$, __S2_CNEIBIO_PACK$_STRING_MAX_LEN );
#define __S2_CNEIBIO_LASTADR_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_CNEIBIO, __LASTADR, __S2_CNEIBIO_LASTADR_STRING_MAX_LEN );
#define __S2_CNEIBIO_SEND$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_CNEIBIO, __SEND$, __S2_CNEIBIO_SEND$_STRING_MAX_LEN );
#define __S2_CNEIBIO_RAUS_STRING_MAX_LEN 40
CREATE_STRING_STRUCT( S2_CNEIBIO, __RAUS, __S2_CNEIBIO_RAUS_STRING_MAX_LEN );
#define __S2_CNEIBIO_MELDUNG_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_CNEIBIO, __MELDUNG, __S2_CNEIBIO_MELDUNG_STRING_MAX_LEN );
#define __S2_CNEIBIO_SENDQ_ARRAY_NUM_ELEMS 100
#define __S2_CNEIBIO_SENDQ_ARRAY_NUM_CHARS 10
CREATE_STRING_ARRAY( S2_CNEIBIO, __SENDQ, __S2_CNEIBIO_SENDQ_ARRAY_NUM_ELEMS, __S2_CNEIBIO_SENDQ_ARRAY_NUM_CHARS );
#define __S2_CNEIBIO_POLLQ_ARRAY_NUM_ELEMS 50
#define __S2_CNEIBIO_POLLQ_ARRAY_NUM_CHARS 2
CREATE_STRING_ARRAY( S2_CNEIBIO, __POLLQ, __S2_CNEIBIO_POLLQ_ARRAY_NUM_ELEMS, __S2_CNEIBIO_POLLQ_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_CNEIBIO )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_STRING_STRUCT( S2_CNEIBIO, __COMMAND );
   DECLARE_STRING_STRUCT( S2_CNEIBIO, __GATEWAYRX );
};

START_NVRAM_VAR_STRUCT( S2_CNEIBIO )
{
   DECLARE_STRING_STRUCT( S2_CNEIBIO, __ADR );
   DECLARE_STRING_STRUCT( S2_CNEIBIO, __PARMS );
   DECLARE_STRING_STRUCT( S2_CNEIBIO, __ANSWER$ );
   DECLARE_STRING_STRUCT( S2_CNEIBIO, __PACK$ );
   DECLARE_STRING_STRUCT( S2_CNEIBIO, __LASTADR );
   DECLARE_STRING_STRUCT( S2_CNEIBIO, __SEND$ );
   DECLARE_STRING_STRUCT( S2_CNEIBIO, __RAUS );
   DECLARE_STRING_STRUCT( S2_CNEIBIO, __MELDUNG );
   DECLARE_STRING_ARRAY( S2_CNEIBIO, __SENDQ );
   DECLARE_STRING_ARRAY( S2_CNEIBIO, __POLLQ );
   unsigned short __IDX;
   unsigned short __OPFER;
   unsigned short __REPEAT;
   unsigned short __ANSHI;
   unsigned short __PACKBYTE;
   unsigned short __CHAR;
   unsigned short __COUNT;
   unsigned short __CHECK;
   unsigned short __SENDQIN;
   unsigned short __SENDQOUT;
   unsigned short __POLLQIN;
   unsigned short __POLLQOUT;
   unsigned short __SCOUNT;
   unsigned short __SCHECK;
   unsigned short __SCHAR;
   unsigned short __SNIBBLE;
   unsigned short __POS;
};



#endif //__S2_CNEIBIO_H__

