#ifndef __S2_XIVAZE_H__
#define __S2_XIVAZE_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_xivaZE_FIRST_DIG_INPUT 0
#define __S2_xivaZE_PREV_DIG_INPUT 1
#define __S2_xivaZE_NEXT_DIG_INPUT 2
#define __S2_xivaZE_LAST_DIG_INPUT 3
#define __S2_xivaZE_BROWSEDISC_DIG_INPUT 4
#define __S2_xivaZE_BROWSEARTIST_DIG_INPUT 5
#define __S2_xivaZE_BROWSEGENRE_DIG_INPUT 6
#define __S2_xivaZE_BROWSEPLAYLIST_DIG_INPUT 7
#define __S2_xivaZE_BROWSEFWD_DIG_INPUT 8
#define __S2_xivaZE_BROWSEBACK_DIG_INPUT 9
#define __S2_xivaZE_BROWSESELECT_DIG_INPUT 10
#define __S2_xivaZE_SEARCHTEXT_DIG_INPUT 11
#define __S2_xivaZE_SEARCHLETTER_DIG_INPUT 12
#define __S2_xivaZE_BROWSEPLAYALL_DIG_INPUT 13
#define __S2_xivaZE_PLAYENTIRELIBRARY_DIG_INPUT 14


/*
* ANALOG_INPUT
*/
#define __S2_xivaZE_TRACKSPERSCREEN_ANALOG_INPUT 0
#define __S2_xivaZE_TRACKSELECTOR_ANALOG_INPUT 1
#define __S2_xivaZE_ZONE_ANALOG_INPUT 2

#define __S2_xivaZE_DISCID$_STRING_INPUT 3
#define __S2_xivaZE_DISCID$_STRING_MAX_LEN 12
CREATE_STRING_STRUCT( S2_xivaZE, __DISCID$, __S2_xivaZE_DISCID$_STRING_MAX_LEN );
#define __S2_xivaZE_ID1$_STRING_INPUT 4
#define __S2_xivaZE_ID1$_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_xivaZE, __ID1$, __S2_xivaZE_ID1$_STRING_MAX_LEN );
#define __S2_xivaZE_ID2$_STRING_INPUT 5
#define __S2_xivaZE_ID2$_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_xivaZE, __ID2$, __S2_xivaZE_ID2$_STRING_MAX_LEN );
#define __S2_xivaZE_ID3$_STRING_INPUT 6
#define __S2_xivaZE_ID3$_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_xivaZE, __ID3$, __S2_xivaZE_ID3$_STRING_MAX_LEN );
#define __S2_xivaZE_ID4$_STRING_INPUT 7
#define __S2_xivaZE_ID4$_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_xivaZE, __ID4$, __S2_xivaZE_ID4$_STRING_MAX_LEN );
#define __S2_xivaZE_ID5$_STRING_INPUT 8
#define __S2_xivaZE_ID5$_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_xivaZE, __ID5$, __S2_xivaZE_ID5$_STRING_MAX_LEN );
#define __S2_xivaZE_ID6$_STRING_INPUT 9
#define __S2_xivaZE_ID6$_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_xivaZE, __ID6$, __S2_xivaZE_ID6$_STRING_MAX_LEN );
#define __S2_xivaZE_ID7$_STRING_INPUT 10
#define __S2_xivaZE_ID7$_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_xivaZE, __ID7$, __S2_xivaZE_ID7$_STRING_MAX_LEN );
#define __S2_xivaZE_ID8$_STRING_INPUT 11
#define __S2_xivaZE_ID8$_STRING_MAX_LEN 2
CREATE_STRING_STRUCT( S2_xivaZE, __ID8$, __S2_xivaZE_ID8$_STRING_MAX_LEN );
#define __S2_xivaZE_GENREMARKER$_STRING_INPUT 12
#define __S2_xivaZE_GENREMARKER$_STRING_MAX_LEN 12
CREATE_STRING_STRUCT( S2_xivaZE, __GENREMARKER$, __S2_xivaZE_GENREMARKER$_STRING_MAX_LEN );
#define __S2_xivaZE_GENRECOUNT$_STRING_INPUT 13
#define __S2_xivaZE_GENRECOUNT$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_xivaZE, __GENRECOUNT$, __S2_xivaZE_GENRECOUNT$_STRING_MAX_LEN );
#define __S2_xivaZE_GENREMEDIAMARKER$_STRING_INPUT 14
#define __S2_xivaZE_GENREMEDIAMARKER$_STRING_MAX_LEN 12
CREATE_STRING_STRUCT( S2_xivaZE, __GENREMEDIAMARKER$, __S2_xivaZE_GENREMEDIAMARKER$_STRING_MAX_LEN );
#define __S2_xivaZE_GENREMEDIACOUNT$_STRING_INPUT 15
#define __S2_xivaZE_GENREMEDIACOUNT$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_xivaZE, __GENREMEDIACOUNT$, __S2_xivaZE_GENREMEDIACOUNT$_STRING_MAX_LEN );
#define __S2_xivaZE_ARTISTMARKER$_STRING_INPUT 16
#define __S2_xivaZE_ARTISTMARKER$_STRING_MAX_LEN 12
CREATE_STRING_STRUCT( S2_xivaZE, __ARTISTMARKER$, __S2_xivaZE_ARTISTMARKER$_STRING_MAX_LEN );
#define __S2_xivaZE_ARTISTCOUNT$_STRING_INPUT 17
#define __S2_xivaZE_ARTISTCOUNT$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_xivaZE, __ARTISTCOUNT$, __S2_xivaZE_ARTISTCOUNT$_STRING_MAX_LEN );
#define __S2_xivaZE_ARTISTMEDIAMARKER$_STRING_INPUT 18
#define __S2_xivaZE_ARTISTMEDIAMARKER$_STRING_MAX_LEN 12
CREATE_STRING_STRUCT( S2_xivaZE, __ARTISTMEDIAMARKER$, __S2_xivaZE_ARTISTMEDIAMARKER$_STRING_MAX_LEN );
#define __S2_xivaZE_ARTISTMEDIACOUNT$_STRING_INPUT 19
#define __S2_xivaZE_ARTISTMEDIACOUNT$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_xivaZE, __ARTISTMEDIACOUNT$, __S2_xivaZE_ARTISTMEDIACOUNT$_STRING_MAX_LEN );
#define __S2_xivaZE_MEDIAMARKER$_STRING_INPUT 20
#define __S2_xivaZE_MEDIAMARKER$_STRING_MAX_LEN 12
CREATE_STRING_STRUCT( S2_xivaZE, __MEDIAMARKER$, __S2_xivaZE_MEDIAMARKER$_STRING_MAX_LEN );
#define __S2_xivaZE_MEDIACOUNT$_STRING_INPUT 21
#define __S2_xivaZE_MEDIACOUNT$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_xivaZE, __MEDIACOUNT$, __S2_xivaZE_MEDIACOUNT$_STRING_MAX_LEN );
#define __S2_xivaZE_PLAYLISTMARKER$_STRING_INPUT 22
#define __S2_xivaZE_PLAYLISTMARKER$_STRING_MAX_LEN 12
CREATE_STRING_STRUCT( S2_xivaZE, __PLAYLISTMARKER$, __S2_xivaZE_PLAYLISTMARKER$_STRING_MAX_LEN );
#define __S2_xivaZE_PLAYLISTCOUNT$_STRING_INPUT 23
#define __S2_xivaZE_PLAYLISTCOUNT$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_xivaZE, __PLAYLISTCOUNT$, __S2_xivaZE_PLAYLISTCOUNT$_STRING_MAX_LEN );
#define __S2_xivaZE_BROWSEID$_STRING_INPUT 24
#define __S2_xivaZE_BROWSEID$_STRING_MAX_LEN 30
CREATE_STRING_STRUCT( S2_xivaZE, __BROWSEID$, __S2_xivaZE_BROWSEID$_STRING_MAX_LEN );
#define __S2_xivaZE_MIN$_STRING_INPUT 25
#define __S2_xivaZE_MIN$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_xivaZE, __MIN$, __S2_xivaZE_MIN$_STRING_MAX_LEN );
#define __S2_xivaZE_TYPE$_STRING_INPUT 26
#define __S2_xivaZE_TYPE$_STRING_MAX_LEN 8
CREATE_STRING_STRUCT( S2_xivaZE, __TYPE$, __S2_xivaZE_TYPE$_STRING_MAX_LEN );
#define __S2_xivaZE_TOTALTRACKS$_STRING_INPUT 27
#define __S2_xivaZE_TOTALTRACKS$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_xivaZE, __TOTALTRACKS$, __S2_xivaZE_TOTALTRACKS$_STRING_MAX_LEN );
#define __S2_xivaZE_CURRENTTRACK$_STRING_INPUT 28
#define __S2_xivaZE_CURRENTTRACK$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_xivaZE, __CURRENTTRACK$, __S2_xivaZE_CURRENTTRACK$_STRING_MAX_LEN );
#define __S2_xivaZE_FIRSTTRACK$_STRING_INPUT 29
#define __S2_xivaZE_FIRSTTRACK$_STRING_MAX_LEN 4
CREATE_STRING_STRUCT( S2_xivaZE, __FIRSTTRACK$, __S2_xivaZE_FIRSTTRACK$_STRING_MAX_LEN );
#define __S2_xivaZE_SEARCHTEXT$_STRING_INPUT 30
#define __S2_xivaZE_SEARCHTEXT$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_xivaZE, __SEARCHTEXT$, __S2_xivaZE_SEARCHTEXT$_STRING_MAX_LEN );
#define __S2_xivaZE_SEARCHLETTER$_STRING_INPUT 31
#define __S2_xivaZE_SEARCHLETTER$_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_xivaZE, __SEARCHLETTER$, __S2_xivaZE_SEARCHLETTER$_STRING_MAX_LEN );
#define __S2_xivaZE_GENRENAME$_STRING_INPUT 32
#define __S2_xivaZE_GENRENAME$_STRING_MAX_LEN 50
CREATE_STRING_STRUCT( S2_xivaZE, __GENRENAME$, __S2_xivaZE_GENRENAME$_STRING_MAX_LEN );
#define __S2_xivaZE_ARTISTNAME$_STRING_INPUT 33
#define __S2_xivaZE_ARTISTNAME$_STRING_MAX_LEN 50
CREATE_STRING_STRUCT( S2_xivaZE, __ARTISTNAME$, __S2_xivaZE_ARTISTNAME$_STRING_MAX_LEN );



/*
* DIGITAL_OUTPUT
*/


/*
* ANALOG_OUTPUT
*/
#define __S2_xivaZE_TRACKFB_ANALOG_OUTPUT 0

#define __S2_xivaZE_XIVA_TX$_STRING_OUTPUT 1
#define __S2_xivaZE_TOPROCESSOR$_STRING_OUTPUT 2


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_xivaZE_MARKER$_STRING_MAX_LEN 12
CREATE_STRING_STRUCT( S2_xivaZE, __MARKER$, __S2_xivaZE_MARKER$_STRING_MAX_LEN );
#define __S2_xivaZE_SEARCHINT$_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_xivaZE, __SEARCHINT$, __S2_xivaZE_SEARCHINT$_STRING_MAX_LEN );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_xivaZE )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_STRING_STRUCT( S2_xivaZE, __DISCID$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ID1$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ID2$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ID3$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ID4$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ID5$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ID6$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ID7$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ID8$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __GENREMARKER$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __GENRECOUNT$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __GENREMEDIAMARKER$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __GENREMEDIACOUNT$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ARTISTMARKER$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ARTISTCOUNT$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ARTISTMEDIAMARKER$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ARTISTMEDIACOUNT$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __MEDIAMARKER$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __MEDIACOUNT$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __PLAYLISTMARKER$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __PLAYLISTCOUNT$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __BROWSEID$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __MIN$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __TYPE$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __TOTALTRACKS$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __CURRENTTRACK$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __FIRSTTRACK$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __SEARCHTEXT$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __SEARCHLETTER$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __GENRENAME$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __ARTISTNAME$ );
};

START_NVRAM_VAR_STRUCT( S2_xivaZE )
{
   DECLARE_STRING_STRUCT( S2_xivaZE, __MARKER$ );
   DECLARE_STRING_STRUCT( S2_xivaZE, __SEARCHINT$ );
   unsigned short __FIRSTAN;
   unsigned short __MEDIACOUNTER;
   unsigned short __BROWSECOUNTER;
   unsigned short __BROWSETYPE;
   unsigned short __MINIMUM;
   unsigned short __TOTALTRACKS;
   unsigned short __CURRENTTRACK;
   unsigned short __FIRSTTRACK;
   unsigned short __SCREEN;
};



#endif //__S2_XIVAZE_H__

